name: Sync LeetCode Past Submissions

on:
  workflow_dispatch: # Allows you to manually click run
  schedule:
    - cron: '0 8 * * *' # Runs automatically every single day at 8 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'my-submissions'
